name: CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run data cleaning
      run: python src/data/data_cleaning.py
    - name: Run feature selection
      run: python src/features/feature_selection.py
    - name: Run preprocessing
      run: python src/features/preprocessing.py
    - name: Run training
      run: python src/models/training.py
    - name: Run Evidently monitoring
      run: python src/monitoring/evidently_monitoring.py
    - name: Deploy to AWS
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      run: |
        terraform init terraform/
        terraform apply -auto-approve terraform/

